# First Stage
FROM microsoft/dotnet:1.1.1-sdk AS build

RUN mkdir /build

WORKDIR /build

COPY dotnetapp.csproj .

RUN dotnet restore

COPY . .

RUN dotnet publish -c Release -o out

# Second Stage
FROM microsoft/dotnet:1.1.1-runtime

WORKDIR /app

COPY --from=build /build/out /app/

CMD ["dotnet", "dotnetapp.dll"]

